### PR TITLE
Add notification of giftcard & fix the bug in sidebar

### PR DESCRIPTION
**Pull request by huonggiangbui**
Demos
responsive
image

### CODE REVIEW

**Review by je888 — CHANGES_REQUESTED** [review]
Hi Giang, for the notification, can you make a cancel button? So that if people close it, they won't see it **in this current visit**. 
For the drawer responsive, we want when people click on the "first/second/third/fourth year" button, the drawer disappears.

**Comment by huonggiangbui** [comment]
> Hi Giang, for the notification, can you make a cancel button? So that if people close it, they won't see it **in this current visit**.
> For the drawer responsive, we want when people click on the "first/second/third/fourth year" button, the drawer disappears.

sure! i will fix it soon

**Comment by huonggiangbui** [comment]
alert
sidebar
@je888 can you check it out?

**Comment by huonggiangbui** [comment]
alert
@je888 here you go!

**Pull request merged**
